controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

supprimer_compte:
    path: '/profil/{id}/supprimerCompte'
    controller: 'App\Controller\DeleteAccountController::supprimerCompte'

